export const HOME = 'HOME';
export const PSYCHOLOGIST = 'PSYCHOLOGIST';
export const PSYCHOLOGIST_APPOINTMENT='PSYCHOLOGIST_APPOINTMENT';
export const PUBLICATIONS = 'PUBLICATION';
export const PUBLICATIONS_PUBLICATION = 'PUBLICATIONS_PUBLICATION';
export const GALLERY = 'GALLERY';
export const GALLERY_CATALOG_IMAGES = 'GALLERY_CATALOG_IMAGES';
export const FORUM = 'FORUM';
export const FORUM_CATALOGS = 'FORUM_CATALOGS';
export const CATALOGS_FORUMS_LIST = 'CATALOGS_FORUMS_LIST';
export const FORUM_CHAT = 'FORUM_CHAT';
export const FORUM_CREATING = 'FORUM_CREATING';
export const WORK_WITH_WEBSITE='WORK_WITH_WEBSITE';

// Auth
export const AUTH_AUTHORIZATION = "AUTH_AUTHORIZATION";
export const AUTH_REGISTRATION = "AUTH_REGISTRATION";
export const AUTH_AUTHENTICATION = "AUTH_AUTHENTICATION";
export const AUTH_FORGET_PASS = "AUTH_FORGET_PASS";
export const AUTH_RESET_PASS = "AUTH_RESET_PASS";
export const CONFIRM_EMAIL = "CONFIRM_EMAIL"

// User
export const USER = "USER";
export const USER_ACCOUNT = "USER_ACCOUNT";
export const EMPLOYEE_ACCOUNT = "EMPLOYEE_ACCOUNT";

//Admin
export const ADMIN_ACCOUNT = "ADMIN_ACCOUNT";
