export const ADD_APPOINTMENT = 'ADD_APPOINTMENT'; //for saga
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT' //for saga
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT' //for saga
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS'; //for saga

export const SET_APPOINTMENTS = 'SET_APPOINTMENTS'; //for redux
export const APPOINTMENT_SPINNER_START = 'APPOINTMENT_SPINNER_START';//for redux
export const APPOINTMENT_SPINNER_END = 'APPOINTMENT_SPINNER_END';//for redux

