// registration types

export const REG_INPUT_FIRST_NAME = 'REG_INPUT_FIRST_NAME';
export const REG_INPUT_LAST_NAME = 'REG_INPUT_LAST_NAME';
export const REG_INPUT_EMAIL = 'REG_INPUT_EMAIL';
export const REG_INPUT_PASSWORD = 'REG_INPUT_PASSWORD';

export const USER_REGISTRATION = 'USER_REGISTRATION';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';

export const INITIAL_STATE_REG = 'INITIAL_STATE_REG';

// authorization types

export const AUTH_INPUT_EMAIL = 'AUTH_INPUT_EMAIL';
export const AUTH_INPUT_PASSWORD = 'AUTH_INPUT_PASSWORD';

export const USER_AUTHORIZATION = 'USER_AUTHORIZATION';
export const USER_AUTHORIZATION_SUCCESS = 'USER_AUTHORIZATION_SUCCESS';

// verified account

export const RESET_INPUT_NEW_PASSWORD = 'RESET_INPUT_NEW_PASSWORD';
export const RESET_INPUT_REPEAT_PASSWORD = 'RESET_INPUT_REPEAT_PASSWORD';

export const USER_FORGET_PASSWORD = 'USER_FORGET_PASSWORD';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';

export const VERIFIED_CODE_INPUT = 'VERIFIED_CODE_INPUT';
export const VERIFIED_EMAIL_INPUT = 'VERIFIED_EMAIL_INPUT'
export const VERIFIED_ACCOUNT = 'VERIFIED_ACCOUNT';
export const VERIFIED_ACCOUNT_SUCCESS = 'VERIFIED_ACCOUNT_SUCCESS';

export const INITIAL_STATE_VERIFIED = 'INITIAL_STATE_VERIFIED';

