export const NEW_FORM_TITLE_INPUT = 'NEW_FORM_TITLE_INPUT';
export const NEW_FORM_DESCRIPTION_INPUT = 'NEW_FORM_DESCRIPTION_INPUT';
export const NEW_FORM_IMAGE_INPUT = 'NEW_FORM_IMAGE_INPUT';

export const ADD_NEW_FORM = 'ADD_NEW_FORM';
export const ADD_NEW_FORM_SUCCESS = 'ADD_NEW_FORM_SUCCESS';

export const LOAD_FORMS = 'LOAD_FORMS';
export const LOAD_FORM_SUCCESS = 'LOAD_FORM_SUCCESS';

export const GET_FROM_BY_ID = 'GET_FROM_BY_ID';
export const GET_FORM_BY_ID_SUCCESS = 'GET_FORM_BY_ID_SUCCESS';
export const FORUM_COMMENTS_RESET = 'FORUM_COMMENTS_RESET'

export const ADD_NEW_FORUM_COMMENT = 'ADD_NEW_FORUM_COMMENT';
export const FORUM_COMMENT_OP_SUCCESS = 'FORUM_COMMENT_OP_SUCCESS';
export const UPDATE_FORUM_COMMENT = 'UPDATE_FORUM_COMMENT';
export const DELETE_FORUM_COMMENT = 'DELETE_FORUM_COMMENT';

export const FORUM_SPINNER_START = 'FORUM_SPINNER_START';
export const FORUM_SPINNER_END = 'FORUM_SPINNER_END';



