export const NEW_FORM_TITLE_INPUT = 'NEW_FORM_TITLE_INPUT';
export const NEW_FORM_DESCRIPTION_INPUT = 'NEW_FORM_DESCRIPTION_INPUT';
export const NEW_FORM_IMAGE_INPUT = 'NEW_FORM_IMAGE_INPUT';

export const ADD_NEW_FORM = 'ADD_NEW_FORM';
export const ADD_NEW_FORM_SUCCESS = 'ADD_NEW_FORM_SUCCESS';

export const LOAD_FORMS = 'LOAD_FORMS';
export const LOAD_FORM_SUCCESS = 'LOAD_FORM_SUCCESS';

export const GET_FROM_BY_ID = 'GET_FROM_BY_ID';
export const GET_FORM_BY_ID_SUCCESS = 'GET_FORM_BY_ID_SUCCESS';

export const FORM_MESSAGE_INPUT = '';
export const MESSAGE_ADD = '';
export const MESSAGE_UPDATE = '';



