
export const GET_GALLERY_CATALOGS = 'GET_GALLERY_CATALOGS'; //for saga
export const ADD_GALLERY_CATALOG = 'ADD_GALLERY_CATALOG'; //for saga
export const UPDATE_GALLERY_CATALOG = 'UPDATE_GALLERY_CATALOG'; //for saga
export const DELETE_GALLERY_CATALOG = 'DELETE_GALLERY_CATALOG'; //for saga
export const GET_GALLERY_IMAGES = 'GET_GALLERY_IMAGES' //for saga

export const SET_GALLERY_CATALOGS = 'SET_GALLERY_CATALOGS';//for redux
export const SET_GALLERY_IMAGES = 'SET_GALLERY_IMAGES'//for redux
export const RESET_GALLERY_IMAGES = 'RESET_GALLERY_IMAGES' //for redux
export const GALLERY_SPINNER_ACTIVATE = 'GALLERY_SPINNER_ACTIVATE'; //for redux
export const GALLERY_SPINNER_DEACTIVATE = 'GALLERY_SPINNER_DEACTIVATE'; //for redux
