
export const LOAD_PUBLICATIONS = 'LOAD_PUBLICATIONS'; //for saga
export const DELETE_PUBLICATION = 'DELETE_PUBLICATION' // for saga
export const UPDATE_PUBLICATION = 'UPDATE_PUBLICATION' // for saga

export const SET_PUBLICATIONS = 'SET_PUBLICATIONS'; //for redux



export const PUBLICATION_SPINNER_START = 'PUBLICATION_SPINNER_START';
export const PUBLICATION_SPINNER_END = 'PUBLICATION_SPINNER_END';