
export const LOAD_PUBLICATIONS = 'LOAD_PUBLICATIONS';
export const LOAD_PUBLICATIONS_SUCCESS = 'LOAD_PUBLICATIONS_SUCCESS';

export const PUBLICATION_SPINNER_START = 'PUBLICATION_SPINNER_START';
export const PUBLICATION_SPINNER_END = 'PUBLICATION_SPINNER_END';