
// User Account
export const USER_ACC_INPUT_FIRST_NAME = 'USER_ACC_INPUT_FIRST_NAME';
export const USER_ACC_INPUT_LAST_NAME = 'USER_ACC_INPUT_LAST_NAME';
export const USER_ACC_INPUT_NICK_NAME = 'USER_ACC_INPUT_NICK_NAME';
export const USER_ACC_INPUT_EMAIL = 'USER_ACC_INPUT_EMAIL';

export const GET_USER_INFO = 'GET_USER_INFO';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE';

export const LOAD_USER_FORUMS = 'LOAD_USER_FORUMS';
export const SET_USER_FORUMS = 'SET_USER_FORUMS';
export const UPDATE_USER_FORUM = 'UPDATE_USER_FORUM';
export const DELETE_USER_FORUM = 'DELETE_USER_FORUM';

export const USER_PROCESS_SUCCESS = 'USER_PROCESS_SUCCESS';


// User appointment
export const APPOINTMENT_INPUT_NAME='APPOINTMENT_INPUT_NAME';
export const APPOINTMENT_INPUT_SESSION_TYPE='APPOINTMENT_INPUT_SESSION_TYPE';
export const APPOINTMENT_INPUT_PHONE_NUMBER='APPOINTMENT_INPUT_PHONE_NUMBER';
export const APPOINTMENT_INPUT_PROBLEM='APPOINTMENT_INPUT_PROBLEM';

