
// User Account
export const USER_ACC_INPUT_FIRST_NAME = 'USER_ACC_INPUT_FIRST_NAME';
export const USER_ACC_INPUT_LAST_NAME = 'USER_ACC_INPUT_LAST_NAME';
export const USER_ACC_INPUT_NICK_NAME = 'USER_ACC_INPUT_NICK_NAME';
export const USER_ACC_INPUT_EMAIL = 'USER_ACC_INPUT_EMAIL';

export const GET_USER_INFO = 'GET_USER_INFO';

// User appointment
export const APPOINTMENT_INPUT_NAME='APPOINTMENT_INPUT_NAME';
export const APPOINTMENT_INPUT_SESSION_TYPE='APPOINTMENT_INPUT_SESSION_TYPE';
export const APPOINTMENT_INPUT_PHONE_NUMBER='APPOINTMENT_INPUT_PHONE_NUMBER';
export const APPOINTMENT_INPUT_PROBLEM='APPOINTMENT_INPUT_PROBLEM';

