
// User Account
export const SET_USER_INFO_ID = 'SET_USER_ID';
export const SET_USER_INFO_FIRST_NAME = 'USER_ACC_INPUT_FIRST_NAME';
export const SET_USER_INFO_LAST_NAME = 'USER_ACC_INPUT_LAST_NAME';
export const SET_USER_INFO_EMAIL = 'USER_ACC_INPUT_EMAIL';
export const SET_USER_INFO_ROLE = 'SET_USER_INFO_ROLE';

export const GET_USER_INFO = 'GET_USER_INFO';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE';

export const LOAD_USER_FORUMS = 'LOAD_USER_FORUMS';
export const SET_USER_FORUMS = 'SET_USER_FORUMS';
export const UPDATE_USER_FORUM = 'UPDATE_USER_FORUM';
export const DELETE_USER_FORUM = 'DELETE_USER_FORUM';

export const USER_PROCESS_SUCCESS = 'USER_PROCESS_SUCCESS';

export const USER_SPINNER_START = 'USER_SPINNER_START';
export const USER_SPINNER_END = 'USER_SPINNER_END';

export const GET_USERS = 'GET_USERS';
export const USER_LOCK = 'USER_LOCK';
export const USER_UNLOCK = 'USER_UNLOCK';

export const SET_USERS = 'SET_USERS';

export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EMPLOYEE_LOCK = 'EMPLOYEE_LOCK';
export const EMPLOYEE_UNLOCK = 'EMPLOYEE_UNLOCK';
export const SET_EMPLOYEES = 'SET_EMPLOYEES';



